deployments:
- build_id: 15ace36e-86a0-467b-ab14-298aeeb01b7e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T11:50:37.672257'
  deployment_id: 07808955-acbe-4e33-9ee4-373928f38555
  image: jhnnsrs/stdlib:0.2.5
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T11:50:33.078895'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.5
- build_id: ce6e3319-4d8a-4e1b-b1dd-149c8df72f00
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T12:44:22.563570'
  deployment_id: f1840b91-7314-4fae-984e-7897fe1e80e7
  image: jhnnsrs/stdlib:0.2.6
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T12:44:09.845473'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.6
- build_id: 0af0da7d-594e-481c-9bba-c124ddb76e4e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T12:57:59.625933'
  deployment_id: 0783ac5c-781d-42a6-a31a-fc2d2a500090
  image: jhnnsrs/stdlib:0.2.7
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T12:57:51.147074'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.7
- build_id: 4e63e0d6-2848-468a-a809-bf873ed91814
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T13:57:57.205575'
  deployment_id: db7a1ea7-8b2d-48c4-8da5-7d5cb90147f2
  image: jhnnsrs/stdlib:0.2.8
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T13:57:49.180609'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.8
- build_id: 9755ae29-2640-4adb-98d6-b353dd1d326b
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T17:23:48.203818'
  deployment_id: 1a0eee91-3099-4ce2-8a95-75b58d4cfa07
  image: jhnnsrs/stdlib:0.2.9
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T17:23:01.809347'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.9
- build_id: a4d9f143-a50a-4aab-9351-68c83e9311f5
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-19T12:20:57.861052'
  deployment_id: bf83d844-b697-418e-ae18-2fbabf89a953
  image: jhnnsrs/stdlib:0.3.0
  manifest:
    author: jhnnsrs
    created_at: '2023-09-19T12:19:31.409849'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.0
- build_id: 12e1acef-185e-4af4-b124-c46da9881f6e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T14:08:01.502813'
  deployment_id: 6a390100-cc06-457b-b7c2-48b37065dfee
  image: jhnnsrs/stdlib:0.3.1
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T14:07:41.806273'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.1
- build_id: 4a6f7c8f-3013-402a-9651-1e4e5935435a
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T15:33:32.726816'
  deployment_id: 69a992ee-f837-4e22-b293-71888819d925
  image: jhnnsrs/stdlib:0.3.3
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T15:33:09.831365'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.3
- build_id: 7da55d0c-1a3c-4360-beb3-f099f61b0011
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T16:15:17.827749'
  deployment_id: 0871b907-6be7-421b-afd4-dc9136ffe90e
  image: jhnnsrs/stdlib:0.3.4
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T16:15:09.135206'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.4
- build_id: a6fceb5e-ebc2-44d5-a7cd-9a7dd2526afc
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T16:18:42.600117'
  deployment_id: b8a96da6-7107-42d3-99f2-3d028efbae28
  image: jhnnsrs/stdlib:0.3.5
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T16:18:34.030889'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.5
- build_id: ac0270a7-466a-4831-802b-18e414a41990
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-26T16:20:04.199234'
  deployment_id: cde2b772-df5f-4528-a3b2-3c04ebefef66
  image: jhnnsrs/stdlib:0.3.6
  manifest:
    author: jhnnsrs
    created_at: '2023-09-26T16:19:53.910920'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.6
- build_id: 1c52bdae-d8c1-49b5-8fba-a18289fc3570
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-10-26T17:03:54.255525'
  deployment_id: a7e38bc2-bb68-4a1b-b502-3be5c397d070
  image: jhnnsrs/stdlib:0.3.8
  manifest:
    author: jhnnsrs
    created_at: '2023-10-26T17:03:36.236634'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.8
latest_deployment: '2023-10-26T17:03:54.266471'
