deployments:
- build_id: 15ace36e-86a0-467b-ab14-298aeeb01b7e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T11:50:37.672257'
  deployment_id: 07808955-acbe-4e33-9ee4-373928f38555
  image: jhnnsrs/stdlib:0.2.5
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T11:50:33.078895'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.5
- build_id: ce6e3319-4d8a-4e1b-b1dd-149c8df72f00
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T12:44:22.563570'
  deployment_id: f1840b91-7314-4fae-984e-7897fe1e80e7
  image: jhnnsrs/stdlib:0.2.6
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T12:44:09.845473'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.6
- build_id: 0af0da7d-594e-481c-9bba-c124ddb76e4e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T12:57:59.625933'
  deployment_id: 0783ac5c-781d-42a6-a31a-fc2d2a500090
  image: jhnnsrs/stdlib:0.2.7
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T12:57:51.147074'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.7
latest_deployment: '2023-08-29T12:57:59.628115'
