deployments:
- build_id: 331b8b05-fd77-49a4-81bc-76b693fe1716
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-10-26T17:10:32.219728'
  deployment_id: 72aba11e-ec41-4650-ae13-9266b1a9bd65
  image: jhnnsrs/stdlib:0.3.9
  manifest:
    author: jhnnsrs
    created_at: '2023-10-26T17:10:13.519743'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.9
- build_id: 2cb1ee3b-fb57-49e8-bff1-227ac52012ea
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-10-30T13:29:43.674877'
  deployment_id: 0f76c04f-734a-4f28-9155-6a614983def1
  image: jhnnsrs/stdlib:0.3.10
  manifest:
    author: jhnnsrs
    created_at: '2023-10-30T13:29:28.571642'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.3.10
latest_deployment: '2023-10-30T13:29:43.676131'
