deployments:
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-11T15:35:45.540213'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:dev
  requirements: []
  scopes:
  - read
  version: dev
