deployments:
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-11T15:35:45.540213'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:dev
  requirements: []
  scopes:
  - read
  version: dev
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-18T12:10:21.713343'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.1
  requirements: []
  scopes:
  - read
  version: 0.0.1
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-18T13:04:51.203345'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.2
  requirements: []
  scopes:
  - read
  version: 0.0.2
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-20T13:03:11.168381'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.3
  requirements: []
  scopes:
  - read
  version: 0.0.3
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-21T15:28:02.789405'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.4
  requirements: []
  scopes:
  - read
  version: 0.0.4
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-21T17:30:51.573471'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.6
  requirements: []
  scopes:
  - read
  version: 0.0.6
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-28T16:32:51.840597'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.7
  requirements: []
  scopes:
  - read
  version: 0.0.7
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-05-02T14:37:08.576336'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.8
  requirements: []
  scopes:
  - read
  version: 0.0.8
latest_deployment: '2023-05-02T14:37:22.412978'
