deployments:
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-11T15:35:45.540213'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:dev
  requirements: []
  scopes:
  - read
  version: dev
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-18T12:10:21.713343'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.1
  requirements: []
  scopes:
  - read
  version: 0.0.1
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-18T13:04:51.203345'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.2
  requirements: []
  scopes:
  - read
  version: 0.0.2
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-20T13:03:11.168381'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.3
  requirements: []
  scopes:
  - read
  version: 0.0.3
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-21T15:28:02.789405'
  definitions: []
  entrypoint: app
  identifier: stdlib
  image: jhnnsrs/stdlib:0.0.4
  requirements: []
  scopes:
  - read
  version: 0.0.4
latest_deployment: '2023-04-21T15:28:11.587465'
