deployments:
- builder: arkitekt.builder.port
  definitions: []
  deployed:
    docker: jhnnsrs/stdlib:3
    runtime: standard
  deployer: arkitekt.deployers.port.dockerbuild
  identifier: stdlib
  scopes:
  - read
  version: '3'
