deployments:
- build_id: 15ace36e-86a0-467b-ab14-298aeeb01b7e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-08-29T11:50:37.672257'
  deployment_id: 07808955-acbe-4e33-9ee4-373928f38555
  image: jhnnsrs/stdlib:0.2.5
  manifest:
    author: jhnnsrs
    created_at: '2023-08-29T11:50:33.078895'
    entrypoint: app
    identifier: stdlib
    requirements: []
    scopes:
    - read
    version: 0.2.5
latest_deployment: '2023-08-29T11:50:37.672284'
