deployments:
- builder: arkitekt.builder.port
  definitions: []
  deployed:
    docker: jhnnsrs/stdlib:3
    runtime: standard
  deployer: arkitekt.deployers.port.dockerbuild
  identifier: stdlib
  scopes:
  - read
  version: '3'
- builder: arkitekt.builder.port
  definitions: []
  deployed:
    docker: jhnnsrs/stdlib:two
    runtime: standard
  deployer: arkitekt.deployers.port.dockerbuild
  identifier: stdlib
  scopes:
  - read
  version: two
- builder: arkitekt.builder.port
  definitions: []
  deployed:
    docker: jhnnsrs/stdlib:three
    runtime: standard
  deployer: arkitekt.deployers.port.dockerbuild
  identifier: stdlib
  scopes:
  - read
  version: three
latest_deployment: '2023-03-23T07:27:42.400693'
